<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r""D:\gitrepo\nlp_practice\bag of words\spam.csv"")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


<h3>Train test split</h3>

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_train)

pandas.Series

In [ ]:
X_train[:4]

4255               How about clothes, jewelry, and trips?
5016    I think the other two still need to get cash b...
5441    By the way, make sure u get train to worc fore...
2363    How are you doing? Hope you've settled in for ...
Name: Message, dtype: str

In [ ]:
type(y_train)

pandas.Series

In [ ]:
y_train[:4]

4255    0
5016    0
5441    0
2363    0
Name: spam, dtype: int64

In [ ]:
type(X_train.values)

pandas.arrays.StringArray

<h3>Create bag of words representation using CountVectorizer</h3>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59146 stored elements and shape (4457, 7749)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7749,))

In [ ]:
X_train_cv.shape

(4457, 7749)

In [ ]:
v.get_feature_names_out()[1771]

'chex'

In [ ]:
v.vocabulary_

{'how': 3526,
 'about': 764,
 'clothes': 1851,
 'jewelry': 3827,
 'and': 963,
 'trips': 7037,
 'think': 6844,
 'the': 6814,
 'other': 5016,
 'two': 7086,
 'still': 6477,
 'need': 4738,
 'to': 6931,
 'get': 3120,
 'cash': 1671,
 'but': 1570,
 'we': 7421,
 'can': 1625,
 'def': 2214,
 'be': 1269,
 'ready': 5607,
 'by': 1584,
 'way': 7416,
 'make': 4328,
 'sure': 6619,
 'train': 7006,
 'worc': 7599,
 'foregate': 2938,
 'street': 6506,
 'not': 4841,
 'shrub': 6134,
 'hill': 3438,
 'have': 3359,
 'fun': 3040,
 'night': 4787,
 'are': 1053,
 'you': 7716,
 'doing': 2390,
 'hope': 3494,
 've': 7261,
 'settled': 6038,
 'in': 3643,
 'for': 2936,
 'new': 4769,
 'school': 5943,
 'year': 7691,
 'just': 3881,
 'wishin': 7552,
 'gr8': 3214,
 'day': 2174,
 'no': 4805,
 'da': 2136,
 'today': 6937,
 'also': 928,
 'forgot': 2947,
 'jordan': 3858,
 'got': 3201,
 'voted': 7328,
 'out': 5027,
 'last': 4025,
 'nite': 4799,
 'good': 3184,
 'morning': 4599,
 'plz': 5277,
 'call': 1600,
 'me': 4416,
 'sir': 6182,

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7749,))

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 764,  963, 1851, 3526, 3827, 7037]),)

In [ ]:
X_train[:4]

4255               How about clothes, jewelry, and trips?
5016    I think the other two still need to get cash b...
5441    By the way, make sure u get train to worc fore...
2363    How are you doing? Hope you've settled in for ...
Name: Message, dtype: str

In [ ]:
X_train_np[0][1771]

np.int64(0)

<h3>Train the naive bayes model</h3>

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [ ]:
X_test_cv = v.transform(X_test)

<h3>Evaluate Performance</h3>

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.91      0.94       152

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators ` for more details.","[('vectorizer', ...), ('nb', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing `.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.None (default) means no character normalization is performed.Both 'ascii' and 'unicode' use NFKD normalization from:func:`unicodedata.normalize`.",None
,"lowercase lowercase: bool, default=TrueConvert all characters to lowercase before tokenizing.",True
,"preprocessor preprocessor: callable, default=NoneOverride the preprocessing (strip_accents and lowercase) stage whilepreserving the tokenizing and n-grams generation steps.Only applies if ``analyzer`` is not callable.",None
,"tokenizer tokenizer: callable, default=NoneOverride the string tokenization step while preserving thepreprocessing and n-grams generation steps.Only applies if ``analyzer == 'word'``.",None


In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       963
           1       0.97      0.91      0.94       152

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

